[manager]

show_hidden = false # Hide hidden files by default

[opener]

play = [
  { run = 'vlc "$@"', orphan = true, for = "unix" },
  { run = 'mpv "$@"', orphan = true, for = "unix" },
]
zathura = [{ run = 'zathura "$@"', orphan = true, for = "unix" }]

[open]
prepend_rules = [{ name = "*.epub", use = "zathura" }]
